/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chair-b5ecdb6253a7454c916954bef6c10251
title: Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Chair = (props) => {

  const group = useRef()

  const { nodes, materials } = useGLTF('/threeJs/chair-transformed.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-337.62, -369.78, -444.19]}>
          <mesh geometry={nodes.Object_2.geometry} material={nodes.Object_2.material} />
          <mesh geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
          <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
          <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chair-transformed.glb')

export default Chair;