/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anthony Yanez (https://sketchfab.com/paulyanez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/facebook-logo-61764fe978014be48d55dd574da03d9c
title: Facebook Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {

  const group = useRef()

  const { nodes, materials } = useGLTF('/threeJs/fbLogo-transformed.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -50]}>
            <mesh geometry={nodes['Facebook_Logo_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/threeJs/fbLogo-transformed.glb')